### ISSUE TITLE
Install capacitor

### ISSUE THREAD

**Issue by pwnz22** [Shathiso/Vue3-Vite-Quasar-starter-template#1]
Hey! Thank you for this awesome template

Can you please help with installing capacitor, when run `quasar mode add capacitor` im getting error `Global Quasar CLI • ⚠️   Error  Unknown command "mode"`

**Comment by Shathiso** [comment]
Hello Valijon,
This starter template is not utilizing the Quasar CLI, which is why the command is not working. I am simply using Quasar as plug-in to Vite to access Quasars UI component Library. Please take a look at the Vite.config.js file to see where I am adding Quasar as a plug-in.
 To achieve what you want, please start a different project by installing the Quasar CLi and following the instructions in the link below to add Capacitor.
Configuring Capacitor | Quasar Framework  
|  
|   
|   
|   |    |

   |

  |
|  
|   |  
Configuring Capacitor | Quasar Framework
 
***@***.***/app-vite) How to manage your Capacitor apps with Quasar CLI.
  |   |

  |

  |

  

Kind Regards 
 
  On Wed, 10 Jul 2024 at 1:00, ***@***.***> wrote:   


Hey! Thank you for this awesome template

Can you please help with installing capacitor, when run quasar mode add capacitor im getting error Global Quasar CLI • ⚠️ Error Unknown command "mode"

**Comment by pwnz22** [comment]
Ahh, okay, thank you :)
